config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'queries#index'
  resources :queries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
  require 'mechanize'

  belongs_to :user
  has_many :query_results, dependent: :destroy

  validates_presence_of :name

  INVALID_TEXT = ['', 'Zaloguj się'].freeze

  def build_query(searched_query)
    results = search_query searched_query

    begin
      ActiveRecord::Base.transaction do
        update! name: searched_query
        results.each do |result|
          next if INVALID_TEXT.include?(result.text)
          query_results.create!(text: result.text, uri: result.resolved_uri)
        end
      end

    rescue ActiveRecord::RecordInvalid => exception
      Rails.logger.info exception.message
      return false
    end
    true
  end

  def self.refresh_queries
    all.each(&:check_refresh)
  end

  def search_query(searched_query)
    url = 'http://google.com'
    agent = Mechanize.new
    page = agent.get(url)

    form = page.form_with name: 'f'
    input = form.field_with name: 'q'
    input.value = searched_query
    new_page =  form.submit
    new_page.links_with href: /url\?q/
  end

  def check_refresh
    new_results = search_query name
    return false if new_results.count == 1

    begin
      ActiveRecord::Base.transaction do
        query_results.each_with_index do |query_result, index|
          next if new_results[index].nil?

          if query_result.text != new_results[index].text || query_result.uri != new_results[index].resolved_uri
            query_result.update(text: new_results[index].text, uri: new_results[index].resolved_uri)
          end
        end
      end
    rescue ActiveRecord::RecordInvalid => exception
      Rails.logger.info exception.message
      return false
    end
    true
  end

end

app/models/query_result.rb
class QueryResult < ApplicationRecord
  belongs_to :query

  validates_presence_of :text, :uri
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :queries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :find_query, only: [:edit, :destroy, :show, :create]
  skip_before_action :verify_authenticity_token

  def index
    @queries = []
    unless current_user.nil?
      @queries = current_user.queries
    end
  end

  def new; end

  def show; end

  def create
    respond_to do |format|
      if !params[:searched].nil? && @query.build_query(params[:searched])
        format.json { render json: { message: 'Query created!', redirect_path: query_path(@query) }, status: :ok }
      else
        format.json { render json:  @query.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def destroy
    respond_to do |format|
      if @query.destroy!
        format.json { render json: { message: 'Query deleted!', redirect_path: queries_path }, status: :ok }
      else
        format.json { render json: { message: 'Something went wrong' }, status: :unprocessable_entity }
      end
    end
  end

  private

  def query_params

  end

  def find_query
    @query = params[:id].present? ? Query.includes(:query_results).find(params[:id]) : current_user.queries.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/common/_navigation.html.haml
%nav.navbar.navbar-expand-lg
  %a{ href: root_path, class: 'navbar-brand' }
    Main Page
  %button.navbar-toggler{ type: "button", "data-toggle": "collapse", "data-target": "#navbarContent",  "aria-controls": "navbarContent", "aria-expanded": "false", "aria-label": "Toggle navigation" }
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#navbarContent
    .navbar-right.pull-right
      %ul.navbar-nav.mr-auto
        -if user_signed_in?
          %li.nav-link.dropdown
            = link_to 'Wyloguj', destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          %li.nav-link
            = link_to "Zaloguj się", new_user_session_path, "data-toggle": "modal",  "data-target": "#login-modal"
          %li.nav-link
            = link_to "Zarejestruj się", new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WynikiGoogle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/queries/index.html.haml
.container
  .row.mt-5.pt-5
    .col-12.text-left
      = link_to 'Add query', new_query_path, class: 'btn btn-primary'
  .row.mt-5
    .col-12
      %table.table
        %thead
          %tr
            %th
              Name
            %th
              Actions
        %tbody
          - @queries.each do |query|
            %tr
              %td
                = query.name
              %td
                = link_to 'Show', query_path(query)
                = link_to 'Edit', edit_query_path(query)
                = link_to 'Destroy', query_path(query), class: 'js-delete-query'

app/views/queries/new.html.haml
.container
  .row.mt-5.pt-5
    .col-12
      %h2
        Enter searched phrase:
      %form
        .form-group
          %input#searchedQuery.js-searched-query.w-100{ name: 'Name' }
        %input.btn.btn-primary.js-search-query{type: "submit", data: {path: queries_path}, name: 'Submit'}

app/views/queries/show.html.haml
.container
  .row.text-center.mt-5
    .col-12
      %h1
        = @query.name
    .col-12
      %table.table
        %thead
          %tr
            %th
              Text
            %th
              Uri
            %th
              Last modified
        %tbody
          - @query.query_results.each do |query|
            %tr
              %td
                = query.text
              %td
                = link_to 'Result link', query.uri
              %td
                = query.updated_at